#!/usr/bin/env python3
"""Claude Code PreToolUse gate: block edits to machine-owned / secret files.

Deterministic, model-independent guardrail. Reads the PreToolUse JSON payload on
stdin and, if the Edit/Write target is a protected file, exits 2 (block) with a
human-readable reason on stderr. Everything else exits 0 (pass through).

Two protected classes:
  * CHANGELOG.md  -- owned by python-semantic-release (`mode=update`); CLAUDE.md
    forbids hand-edits. The fix is a Conventional Commit, never a manual edit.
  * .env / .env.*  -- secrets (gitignored). `.env.example` is exempt.

Pure stdlib: no network, no crm/D365 import -- runs fast and offline on every
Edit/Write. Contract: PreToolUse exit code 2 blocks the tool call and feeds
stderr back to the agent (Claude Code hooks docs).
"""

from __future__ import annotations

import json
import os
import sys

BLOCK = 2


def _reason(file_path: str) -> str | None:
    """Return a block reason if `file_path` is protected, else None."""
    base = os.path.basename(file_path)
    if base == "CHANGELOG.md":
        return (
            "CHANGELOG.md is generated by python-semantic-release and must never be "
            "hand-edited (see CLAUDE.md §Release). Ship a Conventional Commit "
            "subject (`fix:`/`feat:`/breaking) instead — PSR rewrites this file "
            "at release time."
        )
    if base == ".env" or (base.startswith(".env.") and base != ".env.example"):
        return (
            f"Refusing to edit `{base}`: it holds secrets and is gitignored. Edit "
            "`.env.example` for documentation, or change credentials via `crm profile`."
        )
    return None


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read())
    except (ValueError, TypeError):
        return 0
    if not isinstance(payload, dict):
        return 0

    file_path = (payload.get("tool_input") or {}).get("file_path")
    if not isinstance(file_path, str) or not file_path.strip():
        return 0

    reason = _reason(file_path)
    if reason is None:
        return 0
    sys.stderr.write(f"BLOCKED: {reason}\n")
    return BLOCK


if __name__ == "__main__":
    sys.exit(main())
